### PR TITLE
Add FGRibreau/mailchecker

### PR DESCRIPTION
**Pull request by yetithefoot**
Based on issue https://github.com/wesbos/burner-email-providers/issues/232.
Added ~30000 disposable emails

### CODE REVIEW

**Review by emh-rowland-oconnor — CHANGES_REQUESTED** [review]
Please resolve merge conflicts and re-submit.

**Review by emh-rowland-oconnor — APPROVED** [review]

**Comment by legraphista** [comment]
Hey @emh-rowland-oconnor @yetithefoot Please review the changes in the 21ca8342e247e3568929f15f98f2f14f806df36c (this merger), as it has broken the formatting of emails.txt
image

**Comment by legraphista** [comment]
If this is a de-duplicating related incident, i'd be more than happy to submit a dedup script for such needs

**Comment by emh-rowland-oconnor** [comment]
@legraphista Thanks for pointing out. 

Reverted...

I'll re do the PR and merge.

**Comment by emh-rowland-oconnor** [comment]
@yetithefoot Hi. Sorry, I messed up merging this PR so had to revert. Can you please re-submit?

Thank you!

**Pull request merged**
