### PR TITLE
Merged addresses from different git repositories and sorted alphabetically

### PR DESCRIPTION
**Pull request by mconta**

### CODE REVIEW

**Comment by jrupp** [comment]
Whoa whoa whoa... this adds live.com.. which is very much not a burner email provider.. and mail.ru, which is also a real email provider.  This looks bad.

**Comment by emh-rowland-oconnor** [comment]
This repo seems to be a target for bad data recently.

I'm working on my own project for community maintained DEAs.  Details to follow..

**Comment by wesbos** [comment]
Yeah no good 👎

**Comment by mconta** [comment]
Sorry for the bad pull request, in my case I needed to exclude all non business email domains, this is the reason for the presence of live.com and other non burner email providers.

**Pull request closed without merging**
