### PR TITLE
First cleanout of some spamgourmet addresses - see issue #24

### PR DESCRIPTION
**Pull request by mikedlr**
This is the start of cleaning out spamgourmet domains.  N.B. I'm verifying that they fit all the promised criteria before committing so I'll probably do this in several batches.

### CODE REVIEW

**Comment by emh-rowland-oconnor** [comment]
Still looks like a burner email address provider to me.

Wesbos/burner-email-providers is not my list (obviously), so whatever outcome is cool. 

Wesbos is a useful feed for us but not our entire list.

Will not be removing from our list which serves several thousand customers of our email data services.

We vet possible DEA providers against a set of criteria. SpamGourmet still ticks enough of our customers concern boxes to stay listed.

If SpamGourmet can get de-listed here, who else is eligible perhaps?

**Comment by emh-rowland-oconnor** [comment]
Seems like I'm not the only one to take a view on spamgourmet:

[These guys](https://preventdisposable.com/) list it as burner too. Just checked all of the proposed deletions in this PR.

**Comment by 1337** [comment]
I would also say spamgourmet (provider of "disposable email addresses", like they say in their page title) qualifies as a "burner email provider". Main problem with my saying that is the README in this repo:

> I'm okay with people using burner email addresses to get my free content, I just need to be able to filter them out of my list so it doesn't drive up bounces and hurt deliverability. 

and issue #24 claims that spamgourmet does not bounce.

**Comment by emh-rowland-oconnor** [comment]
@1337 Sure. Good spot!

If the intent of this list is to prevent bounces then fine.

Customers of my companies DEA list are more worried about the propensity towards general anti-social behaviour (e.g spamming forums) that tends to go with the use of burner email addresses.

Different use cases (hard bounces versus mitigating anti-social online behaviour).

Thanks for pointing out.

**Comment by mikedlr** [comment]
@emh-rowland-oconnor  on your criteria - "propensity towards general anti-social behaviour (e.g spamming forums)" - Spamgourmet has extremely strict [terms of service](https://www.spamgourmet.com/index.pl?printpage=terms.html) and I believe, from following their [support forum](http://bbs.spamgourmet.com/viewforum.php?f=4&sid=ec0e119f2363ccdff1c609cf31987213) that they enforce them.  

Rowland, If you have seen spam source from spamgourment addresses, have you tried abuse reporting it?  If that's not required in your criteria then you should probably be blocking also gmail.com, yahoo.com and hotmail.com which also offer open accounts to anyone who wants to sign up?  If it is, then please try and I think you will find that spamgourmet not only is extremely anti-spam; has good terms of service but will also ["roll over like a puppy dog"](http://bbs.spamgourmet.com/viewtopic.php?f=7&t=1657&sid=ec0e119f2363ccdff1c609cf31987213) if law enforcement turn up with an appropriate information request.  

This is not the service your spammer wants to be using for their burner email addresses.

**Comment by emh-rowland-oconnor** [comment]
@mikedlr Thank you for your observations. This (DEAs) is an interesting area for sure. For reasons of client and commercial confidentiality, I can only go so far in this debate on the specifics re the ethics of DEAs and specifically spamgourmet and its operating ToS / AUP. I can say, however, that the appetite for up to date lists of DEA providers is currently fairly high in not only the B2C space (e.g. forums etc) but also in B2B with some well known names in digital forensics taking the lead.

I'll leave it to your imagination to ponder on the possible reasons behind this desire for data on DEAs and also why this GitHub repo for burner email address providers ranks so well in organic search.

You rightly point out that users can use freemail accounts (e.g. Hotmail, Gmail etc) to create anonymous accounts to sign up for services. In our company we keep lists of freemail providers separately to DEA and each is scored for risk accordingly. I suspect that your will point out that  spamgourmet terms of service are different than other DEA providers which is probably true. 

To scope out the general issues with DEA providers as a whole, for a general DEA / freemail compare / contrast our company used a combination of 3rd party industry analysis (content that our company paid for and is under license I cannot re-publish in entirety) together with our own metrics to determine similarities / differences as follows:

## Freemail (e.g. Hotmail) and DEA (e.g. mailinator)

### Compared

* Permits anonymous registration
* Can (but not obliged to) track user behavior via server side logs
* Allows users to send / receive email

### Contrasted

* Large Freemail ISPs are required to have robust procedures and policies for user activity logging (IP, device and SMTP tracking).
* Large Freemail IPSs generally have more robust barriers in place to prevent fraudulent signups.
* Average longevity of freemail email addresses is significantly higher than DEAs (which by their very definition are "disposable" / temporary.
* It takes longer to sign up for freemail than DEA.
* Freemail often requires statement of alternative email address as part of sign up.
* Freemails often require MFA (e.g.SMS) verification on registration.
* Most DEAs require no sign up at all.
* Freemail offers mailbox security through user identity isolation. There is often no mailbox security with DEAs as anyone can use any mailbox name (a historic problem for spamgourmet too as our R&D team inform me)

On the basis of this research our company scores freemail / DEAs very differently in terms of risk.

## Wrapping up
I can understand to an extent where you're coming from (spamgourmet is the "good guy" in a sea of DEAs). I can't help thinking that the DEA ship has already set sail though and ultimately very few people will care if one DEA provider is more honorable than others.

For our companies customers, the message that we get is simply "help us keep DEAs out of our systems". This is why our company invests time, money and resource in meeting this demand.

I fear that any mail service provider with the words "Disposable Email Address" in its tagline proposition faces an uphill struggle against increasing resistance from the wider service operator community not wanting to do business. e.g. Is Facebook still blocking spamgourmet addresses for policy /risk reasons?

Back to my original note, I'm not the owner of this repo so the ultimate decision on your PR being accepted lies with @wesbos . 

I respect your point of view and wish you good fortune and peace.

**Comment by mikedlr** [comment]
@emh-rowland-oconnor ;  thanks for your long and throughtful response.  I appreciate your engaging here.  

There's one comment I don't fully understand in your comment;  could you please expand:

> There is often no mailbox security with DEAs as anyone can use any mailbox name (a historic problem for spamgourmet too as our R&D team inform me)

Spamgourmet has always provided user specific sign up linked to an alterate email address.  Are you suggesting some early problem with this?  

First let me specifically comment that I am (as I made clear earlier) separating services like mailinator which are true "disposable" email services from spamgourmet, and to some extent others like it, which do not match with your description.  

To give a specific case where I think your service's current design is damaging your customer's commercial success, I personally have ongoing commercial relationships dating back from 2007 with large European travel companies (car hire and flight) where I have spent thousands of pounds on their special offers.  This is beneficial on both sides because I travel when they have low demand and getting lower prices whilst giving them business where otherwise they would have none.  When I do not have this relationship it costs me extra time to find equivalent offers, but less time than dealing with spam on my abandoned old email addresses cost me.  

I, like many other  only enter into these (solicited commercial email) relationships because I have access to Spamgourment.  Before that I did not.  Currently I will reject 99% of cases where spamgourmet does not work.  This means that your customers lose money that could otherwise be available to them through use of your service as may currently be designed.  Whether that financial loss is outweight by reduced other costs I'm unable to tell.  Now let me address some of your points:

Very important is that, in a number of cases, if I had been using a normal email address, I would have believed that my email address was being leaked by specific commercial companies leading to me being spammed.  In fact, because I used spamgourmet I was able to detect either security violations or other entities leaking this information.  This protects my ongoing commercial relationships with companies I would otherwise have lost trust in.  

So comments to your specific facts:

### spamgourmet and mailnator contrasted in context

* spamgourmet provides more logging than mailinator for sure - the log registration IP and keep mail /smtp logs for a period
* spamgourmet actually does have a signup procedure and that procedure is designed (using CAPTCHA + blocking) to 
* spamgourmet implements mail sending rate limitations (impossible with mailinator since there's no user account)
* spamgourmet addresses may live for a very long time (as mentioned, I have active ones around 9 years old) 
* spamgourmet requires an alternate email address during signup; both through confirmation and through not working at all without one (there's no web based mail reading interface as in mailinator)
* creation of a new account is a relatively slow process (CAPTCHA / details / confirmation mail / setup / go) although a sub email address (like a gmail   subaddress+account@gmail.com) address is instant
* spamgourmet implements user identity isolation since any given sub-address belongs to one account which can only be used by the registered user.  

### spamgourmet and mailnator compared

* as you stated spamgourment does have multiple domains  - though so does google (googlemail/gmail etc) - I've listed only ones that are visibly tied to spamgourmet
* spamgourmet does not require MFA - though that's also true of a number of other major mail services I signed up for recently.  

In summary, whether spamgourmet counts as DEA would depend on use case:

* I want to build long term trusting relationships with customers - Spamgourmet is good for this - should not count as DEA
* I want to allow users to post to my system without spamming - Spamgourmet should be good for this - should not count as DEA
* I want to ensure a long term relationship with one user and not have an account used by multiple users - Spamgourment should be okay for this unless they have allowed people signing up with mailinator
* I want to ensure I have a user's true email address so I can follow them around on the internet - Spamgourmet is not good for this.  Don't try to follow spamgourmet users.  
* I want to spam people and know it's being delivered - Spamgourmet is not suitable for this.  Don;t add spamgourmet addresse to your spamming lists 

I would recommend either not listing spamgourmet as a DEA or separating DEA's into two categories making it clear that spamgourmet is probably better for ongoing commercial relationships than a typical freemail provider since it protects trust in the email sender.  

In the current context;  avoiding bounces and other problems associated with a DEA, spamgourmet is clearly not creating the problems of a DEA.

**Comment by emh-rowland-oconnor** [comment]
Hi @mikedlr .

Very good points made - thank you.

As requested, to explain my point on mailbox security, please refer to 3rd party review dated June '15 [here](http://uk.pcmag.com/spamgourmet/29728/review/spamgourmet), paragraph 2

> For example, crazylegs.4.larryseltzer@spamgourmet.com will be able to receive four messages, and then senders will get error messages. The problem is, anyone can send you a message using a disposable account that you did not create: for example, IAMSPAM.20.larryseltzer@spamgourmet.com.

Hope this clarifies.

Shared mailbox IDs is an issue shared with many other DEAs such as mailinator.

## On the question of listing spamgourmet as a DEA
Spamgourmet mentions in it's title and 3 times on front page copy of it's website, a "disposable email address" provider? It is also listed as a DEA provider in directories / reviews such as:

* [w3guy.com](http://w3guy.com/disposable-email-address/)
* [ghacks.net] (http://www.ghacks.net/2012/05/31/the-ultimate-disposable-email-provider-list-2012/)
* [about.com] (http://email.about.com/od/disposableemailservices/tp/disposable.htm)

This repo is a list of DEAs. 

Spamgourmet by it's own and others definitions is a DEA provider. 

The two ends of the rope seem to join. Am I missing something here?

What is spamgourmet trying to be is the ultimate question I suppose? Is it a DEA? It it a Freemail? Is it a spam application? Where would it stand in the classification of DEA, freemail, anti-spam? this would be a clarification point in the sites / services marketing messaging surely?

At this time, whilst it is clearly advertising as a DEA, is it surprising that spamgourmet is included on DEA lists?

## On the question of building long term relationships with clients arriving with DEAs
Many of our clients (and our company too) have been historically ripped off by individuals hiding behind DEAs (we have our own evidence in terms of fraud history to support this assertion). I think that many vendors have simply had enough hence why they turn to lists such as this repo or industrial verification services such as ours. Closing the doors to DEA registrations makes a tangible, immediate effect.

Sure, vendors are going to lose a few potential legitimate customers who don't entirely trust  enough from the get-go to provide a real identity. However, we took the informed view that the loss of this opportunity from blocking DEAs was far less than the loss directly attributable to the consequences of allowing DEAs through.

### A question of trust
Most of our potential customers taking up trials are happy to engage with us on an open and honest basis and provide full disclosure on company details (e.g. domain, telephone number) from the initial touch point. 

We provide full disclosure on privacy and business policies, a verifiable physical address, company registration number and a phone number. (Interestingly, spamgourmet or any other DEA provider that we've investigated for that matter seems to provide any physical contact information)?

Ultimately, a supplier and customer need to arrive at a point of mutual trust in order to do business. For every supplier, this is an individual choice. For our company, having been burned heavily from DEA registrations in the past, we take a policy choice of not allowing DEAs. By DEA, we mean anything that describes itself as a DEA. At this time, we make no differentiation between DEA good / DEA bad. DEA is DEA and gets classified as such.

How would a shopkeeper feel if a customer walked into their shop wearing a balaclava? Similar analogy with DEAs perhaps?

DEAs = good for customers, bad for suppliers. Like many of the consumers of this DEA repo, I am a supplier. As a customer of services, I can see how spamgourmet works well for you though.

## The question?
I'm not sure what you are asking for here. Is it removal of spamgourmet from this / other list of DEAs? If so, would it perhaps be a good start point to ask spamgourmet to change its messaging / description away from being a DEA provider?

Not my repo though, so not my decision. Full respect to @wesbos with a difficult choice to make here. Am cool with whatever is decided - it if were my repo running on goodwill, I would probably accept the PR for a quiet life and move on.

However, for our company, we continue the mission to seek and identify DEA providers. It is a perpetual, mundane and thankless task. Good news is that we are creating jobs and solving a pain point for many online businesses. Not such good news if you are a consumer of DEA services though as more and more doors (i.e. registration pages) close to DEAs (sorry!).

Thank you again for your point of view. I'm sure that our differing perspectives will resound with the wider community for a long time to come. We've all gotta do what we gotta do (use DEAs or list 'em).

Am still respecting your position BTW. 

Kind regards & peace..

**Comment by mikedlr** [comment]
> I'm not sure what you are asking for here. Is it removal of spamgourmet from this / other list of DEAs? 

From the burner-email-providers list I'd like removal since spamgourmet doesn't provide the problems they are attempting to avoid (bounces and other problems with mail delivery) thus this listing is incorrect.  

From you / other DEA blocklists which won't completely delist spamgourmet I'd like a) clarification of your aims and opinion (think this has been achieved - thanks) and b) to strongly suggest you give your customers the possibility to see two classifications where mailinator would be in one and spamgourmet would be in a different one. 

Overall, I want to achieve a "trust but verify" stance.  There are a number of times when I get unexplained, apparently unsolicited commercial email.  When I am able to identify the business relationship that caused them then I able to either unsubscribe from a list or simply accept the mail, where in other situations I would simply use gmail features to report the sender as a spammer.  I've already started working with DEA list customers.  At least one (the one through which I came across this list) agrees with me and, as I understand it, will use the same parsing scheme on spamgourmet as they use on gmail enabling me to protect them from being listed as spammers.  

> If so, would it perhaps be a good start point to ask spamgourmet to change its messaging / description away from being a DEA provider?

Yes;  that's an interesting comment.  I will take that up in their forum.  They are a volunteer service so I'm not sure how much effort would be available to change either message or technology.  Let's see.  In any case, the clear definition you have given above helps defining differences between the different systems as seen by you.  

> >   For example, crazylegs.4.larryseltzer@spamgourmet.com will be able to receive four messages, and then senders will get error messages. The problem is, anyone can send you a message using a disposable account that you did not create: 

This review you have quoted is disconcertingly incorrect in several aspects e.g. 

* mail delivery to an expired address does not create an error - instead it is accepted, logged and then discarded which enabes the user to reactivate the address if valuable content is being lost
* there is a user option of whether to accept any address variant or reduce that to specifically chosen ones
* spamgourmet addresses do not disappear even if used by a spammer - exclusive senders can send indefinitelly in any case

I would recommend ignoring it and testing spamgourmet advanced mode yourself directly.

> DEAs = good for customers, bad for suppliers.

I think that in most cases what is good for your customers is good for you in the long term.  Eventually a competitor finds out how to deliver the customer value without losing out.  The question in this case should be how to deliver DEA benefits (security, verification and pseudonoymity) without DEA disadvantages (abuse and full anonymity).  This would be good for both customers and suppliers.

**Comment by emh-rowland-oconnor** [comment]
Unable to remove from list as per service own tagline:

> spamgourmet - free disposable email addresses, strong spam blocker, short learning curve

**Pull request closed without merging**
