### PR TITLE
Add buzblox.com, gonetor.com, mailifyy.com and related domains

### PR DESCRIPTION
**Pull request by Igloczek**
Add buzblox.com, gonetor.com, mailifyy.com  and related domains

https://verifymail.io/domain/buzblox.com
https://verifymail.io/domain/gonetor.com

### CODE REVIEW

**Comment by emh-rowland-oconnor** [comment]
thank you.

**Comment by nullpainter** [comment]
This has added my personal `deity.co.nz` domain which is now causing havoc with my email. This is not, nor has ever been a burner domain. 

https://github.com/wesbos/burner-email-providers/issues/459

**Comment by wesbos** [comment]
@Igloczek Where did you get this list? Seems like many on here are not real email domains

**Comment by tompec** [comment]
The PR should be reverted. More domains from the PR are not disposable and have been added simply because they have `forwardemail.net` MX records (e.g., `calvarylufkin.org`).
These domains appear to have been incorrectly flagged by verifymail.io, the source used by @Igloczek.

Large lists of thousands or even hundreds of domains should not be added all at once, as it is impossible for maintainers to verify each one.

**Comment by nullpainter** [comment]
Ah - that would be why my domain was on there. I use the free tier of https://forwardemail.net/ so use `forwardemail.net` MX records (temporarily disabled for `deity.co.nz` as I paid for a month's enhanced service so I could actually have email working...)

**Comment by nullpainter** [comment]
> The PR should be reverted. More domains from the PR are not disposable and have been added simply because they have `forwardemail.net` MX records (e.g., `calvarylufkin.org`). These domains appear to have been incorrectly flagged by verifymail.io, the source used by @Igloczek.
> 
> Large lists of thousands or even hundreds of domains should not be added all at once, as it is impossible for maintainers to verify each one.

FWIW, I have emailed `verifymail.io` to alert them of their misclassification.

**Comment by Igloczek** [comment]
@wesbos "root" domains: `buzblox.com,` `gonetor.com`, `mailifyy.com` are coming from my manual review, they are related to some fraudulent activities in my apps like creating tons of accounts to abuse free tier, or using fake credit cards for payments.

All the "related" domains are from verifymail.io, as @tompec said.

**Comment by Igloczek** [comment]
I've created a PR that removes all domains related to forwardemail.net - #461

**Comment by nullpainter** [comment]
> But I disagree with the opinion about adding lots of domains at once, since you would almost always either have an incomplete list, so the price of occasional false positives doesn't seem to be very high.

Speaking as somebody who has lost emails because of this PR and then had to spend money to pay for a premium service to bypass use of this service, I strongly disagree.

**Pull request merged**
