### PR TITLE
Update emails.txt

### PR DESCRIPTION
**Pull request by tuptuptuu**
add hey.com
7BCBF776-00DE-4A1B-A8D9-79D5D3D9B4B1

### CODE REVIEW

**Comment by emh-rowland-oconnor** [comment]
Thank you

**Comment by tompec** [comment]
Quick heads up, hey.com is not a disposable domain.
It's a paid email service that shouldn't be blocklisted.
Even though the signup flow on iOS says 'temp mail', it requires a password and a secondary email to sign up.

**Comment by tuptuptuu** [comment]
@tompec The account expires in 14 days, it's definitely disposable. They ask for a password, but don't verify the secondary email address. hey.com also offers a paid email service, but these disposable emails are free.

Note that this list also considers cock.li to be a disposable email provider, those accounts don't even expire.

**Comment by tompec** [comment]
They are disposable, but I think that you'll end up blocking more valid emails than "disposable" emails.

I would suggest you to block those emails with a regex since the generated emails seem to follow the same pattern (eg. 0000-0000-0000@hey.com).

I agree that cock.li shouldn't be in that list either.

**Comment by emh-rowland-oconnor** [comment]
@tompec Thank you for pointing this out.

As further investigation, I was able to sign up for a hey.com account using a @mailinator.com address as a secondary email backup.

As an anonymous user, therefore, it is possible to sign up for a @hey.com and get a temporary email address that can be used to send and receive emails.

**Comment by dhh** [comment]
This is a complete misnomer. HEY is a new email service with over 150,000 users and thousands of paying accounts. There is a separate service mandated by Apple that uses a specific 12 digit email address in the form of ####-####-#### that can be used for 14 days. You could create a similar address for a similar purpose on Gmail or any other service. These addresses are heavily limited and scrutinized to prevent abuse. Please revert this PR. You can find more information about HEY on https://hey.com. Thank you.

**Comment by dhh** [comment]
This user has been created solely for the harassment of HEY. See the rejection in other similar repos: https://github.com/ivolo/disposable-email-domains/pull/825

**Comment by tuptuptuu** [comment]
@dhh So how many of those 150000 addresses will still be working after 2 weeks? Presumably only the “thousands of paying accounts”.

> You could create a similar address for a similar purpose on Gmail or any other service. 

At least those addresses don’t expire. Gmail has very strong anti-abuse measures, from behavioural analysis to phone verifications. 

I had no trouble creating an expiring hey.com address using an OVH datacenter IP and a fake email address. You don’t even verify the secondary email you ask for.

> These addresses are heavily limited and scrutinized to prevent abuse.

Couls you explain exactly how this is supposed to work? You haven’t even bothered to add email or phone verification, are you just talking about ratelimiting?

> This user has been created solely for the harassment of HEY

Don’t you think this is a rather childish accusation? You offer disposable addresses on this domain, of course you’ll be added to DEA provider lists. 

There’s an easy solution available to you, just disable this feature until you can put these accounts under a different domain.

**Comment by Phillipus** [comment]
+1 for reverting this merge request. The account of @tuptuptuu has been created solely as a sock puppet account to harass @dhh and hey.com based on a grudge.

See https://github.com/micke/valid_email2/pull/153

**Comment by tuptuptuu** [comment]
>sock puppet

[I don't think this word means what you think it means](https://en.wikipedia.org/wiki/Sockpuppet_\(Internet\))

>harass @dhh and hey.com based on a grudge.

what makes you think this?

**Comment by tuptuptuu** [comment]
> Hi! Could you please revert this merge request as it seems that the user tuptuptuu was only created to promote this domain as "disposable domain". Hey.com is a valid email provider.
> [ivolo/disposable-email-domains#825 (comment)](https://github.com/ivolo/disposable-email-domains/pull/825#issuecomment-651586238)

Are you saying that hey.com doesn't offer disposable randomized @hey.com addresses that expire in 14 days as is visible in the screenshot?

**Comment by wesbos** [comment]
I reverted it. Definitely not the same thing as gmail, but will have to keep an eye on it as it could be abused. It’s a tricky one since it’s the same domain as legit emails.

**Comment by tuptuptuu** [comment]
> I reverted it. Definitely not the same thing as gmail, but will have to keep an eye on it as it could be abused. It’s a tricky one since it’s the same domain as legit emails.

Are you also going to remove cock.li addresses then?

**Comment by wesbos** [comment]
only if we also do updog

**Comment by tuptuptuu** [comment]
updog is also a perfectly good provider, they should not be listed

**Comment by joshmanders** [comment]
> only if we also do updog

What's updog?

**Comment by tompec** [comment]
@wesbos This might be a good time to explain in the readme what you consider being a "burner email provider" to help people contribute and prevent future issues like this one.

**Pull request merged**
