### PR TITLE
more emails

### PR DESCRIPTION
**Pull request by skgith1**

### CODE REVIEW

**Comment by emh-rowland-oconnor** [comment]
Thank you.

**Comment by wesbos** [comment]
What is the purpose of the extra file here?

**Comment by emh-rowland-oconnor** [comment]
Sorry. I hadn't noticed the changes were submitted as an extra file. 
I'll get it merged into the main file.

**Comment by skgith1** [comment]
Sorry, new to git and did not know how to do this properly, I have more is there a better way for a novice to submit? :)

**Pull request merged**
