### PR TITLE
Domain list pruner with DNS MX checks

### PR DESCRIPTION
**Pull request by fmalina**
Added an MX record checker for email domains.
It's an example script to help prune the domain list to active ones.

Imagine this is a 404 checker for a list of links.

Offered for your consideration and further hacking.
Please test and review. Use at your peril.

### CODE REVIEW

**Comment by emh-rowland-oconnor** [comment]
Hi @fmalina 

Thank you kindly for the Python script. Great work!

I can see how this works. One question/concern: If we run this script on a schedule, is it possible for a DEA provider to temporarily remove MX records to get permanently removed from this list only to subsequently re-introduce MX records once they are clear of this list?

**Comment by kimpenhaus** [comment]
Hi all,

while putting it on cron couldn't you just add a sleep / random delay combination for time variation into the cron? Like mentioned [here](https://github.com/taw00/howto/blob/master/howto-schedule-cron-jobs-to-run-at-random-intervals.md), adopted to the system hosting the cron and with a more random timespan like 3-5 minutes ;-)

**Comment by emh-rowland-oconnor** [comment]
@kimpenhaus
All fantastic suggestions! I can see how this can work. It will need some compute hosting somewhere ($) and some dev time to get up and running.

As an aside (and in full disclosure), I am the owner of a company that performs thorough DEA identification using sophisticated dynamic heuristics and AI to deliver ID of a very high proportion of DEAs even for the more tricky ones (e.g. emailondeck). The service currently is part of our commercial packages and is somewhat of a USP for us due to it's broad coverage. 

So here's the thing, if were now looking at active compute supplementing the wesbos list, someone has to pay for this. It could be my company but this might create a conflict of interest (where paid for and free, community services start to blur).

In all of this, I am absolutely committed to calling out the DEA providers because fundamentally I believe that on balance no good comes from using DEAs from both a business and consumer perspective.

Please leave this with me to ponder some more. I'll need a couple of weeks to discuss with stake holders.

Thanks again for the suggestions.

**Comment by kimpenhaus** [comment]
The cron stuff is doable without any further development effort (on the prune script). If you want to be more safe with deletiono you could prune e.g. 3 times into different files and then delete only those being in none of those 3. In combination with a random execution of those 3 (or n) in a certain timespan I assume it would be pretty reliable.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by secit-pl** [comment]
@emh-rowland-oconnor how much compute power you expect to be needed? I guess I can help :)

**Comment by tompec** [comment]
Just a friendly reminder that a domain can receive emails with no MX records.
https://tools.ietf.org/html/rfc5321#section-5

Therefore you should also check for A and AAAA records before deleting a domain from the list.

**Comment by ndmgrphc** [comment]
Happy to donate $60 for this.

**Comment by fmalina** [comment]
:) Thanks https://PayPal.me/fmalina
I’ll give you an update in a forked repo.

**Review by emh-rowland-oconnor — APPROVED** [review]

**Comment by emh-rowland-oconnor** [comment]
Thank you

**Pull request merged**
