### PR TITLE
Add clipmail.eu

### PR DESCRIPTION
**Pull request by nremond**
Cf: http://www.clipmail.eu/

### CODE REVIEW

**Comment by wesbos** [comment]
thanks!

**Comment by vineshkaveti** [comment]
It would be nice if this list is available as JSON service

**Comment by nremond** [comment]
Here is the URL to have this list "as a service": https://raw.githubusercontent.com/wesbos/burner-email-providers/master/emails.txt

**Comment by letz** [comment]
@vineshkaveti I made one based on this list 

https://fake-emails.herokuapp.com

**Pull request merged**
